name: "provision-with-micromamba"
description: "provision a CI instance using micromamba"
branding:
  icon: "chevrons-right"
  color: "green"
inputs:
  environment-file:
    description: >-
      The environment.yml or .lock file for the conda environment.
      If 'false', no enviroment will be created (only Micromamba will be installed)
      and you should provide 'channels'.
    required: true
    default: environment.yml
  environment-name:
    description: >-
      The name of the conda environment (defaults to name from the environment.yml file).
      Required if 'environment-file' is a '.lock' file or 'false'.
    required: false
  micromamba-version:
    description: >-
      Version of micromamba to use, eg. '0.20' (default 'latest').
    required: false
    default: "latest"
  extra-specs:
    description: >-
      Additional specifications (packages) to install.
      Pretty useful when using matrix builds to pin versions of a test/run dependency.
      For multiple packages, use multiline syntax (see examples).
      Note that selectors
      (e.g. `sel(linux): my-linux-package`, `sel(osx): my-osx-package`, `sel(win): my-win-package`)
      are available.
    required: false
    default: ""
  channels:
    description: >-
      Comma separated list of channels to use in order of priority (eg., `conda-forge,my-private-channel`)
    required: false
    default: ""
  cache-downloads:
    description: >-
      If 'true', cache downloaded packages across calls to the provision-with-micromamba action.
      Cache invalidation can be controlled using the 'cache-downloads-key' option.
    default: false
  cache-downloads-key:
    description: >-
      Custom download cache key used with 'cache-downloads: true'.
      The default download cache key will invalidate the cache once per day.
    required: false
  cache-env:
    description: >-
      If 'true', cache installed environments across calls to the provision-with-micromamba action.
      Cache invalidation can be controlled using the 'cache-env-key' option.
    default: false
  cache-env-key:
    description: >-
      Custom environment cache key used with 'cache-env: true'.
      With the default environment cache key, separate caches will be created for each
      operating system (eg., Linux) and platform (eg., x64) and day (eg., 2022-01-31),
      and the cache will be invalidated whenever the contents of 'environment-file' or 'extra-specs' change.
    required: false
  # cache-env-always-update:
  #   description: >-
  #     (Not implemented)
  #     If 'true', run 'micromamba update' even if the environment was restored from cache
  #     to make sure your environment is always up-to-date.
  #   default: false

runs:
  using: "node16"
  main: "dist/main/index.js"
  post: "dist/post/index.js"
