name: Test options
on:
  push:
    branches:
      - main
  pull_request: null

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_enviroment_file_and_enviroment_name:
    name: Test environment-file, environment-name, extra-specs, log-level
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        pytest: ["6.1", "6.2"]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          environment-file: false
          environment-name: nofile

      - name: install mamba
        uses: ./
        with:
          environment-file: environment.yml
          environment-name: myenv
          extra-specs: |
            pytest=${{ matrix.pytest }}
            python=3.8.8
          log-level: debug

      - name: run python in powershell
        shell: powershell
        run: |
          where micromamba
          micromamba info
          python -VV
          python -c "import numpy"
        if: runner.os == 'Windows'

      - name: run python in bash
        run: |
          which micromamba
          micromamba info
          python -VV
          python -c "import numpy"
        if: runner.os != 'Windows'

      - name: test environment name in powershell
        shell: powershell
        run: |
          python -c "import os; env = os.environ['CONDA_PREFIX'].split('\\')[-1]; assert env == 'myenv'"
        if: runner.os == 'Windows'

      - name: test environment name in bash
        run: |
          python -c "import os; env = os.environ['CONDA_PREFIX'].split('/')[-1]; assert env == 'myenv'"
        if: runner.os != 'Windows'

      - name: check python version in powershell
        shell: powershell
        run: |
          python --version
          python -c "import platform; assert platform.python_version() == '3.8.8'"
        if: runner.os == 'Windows'

      - name: check python version in bash
        run: |
          python --version
          python -c "import platform; assert platform.python_version() == '3.8.8'"
        if: runner.os != 'Windows'

      - name: check pytest version in powershell
        shell: powershell
        run: |
          pytest --version
          python -c "import pytest; assert pytest.__version__.startswith(str(${{ matrix.pytest }}))"
        if: runner.os == 'Windows'

      - name: check pytest version in bash
        run: |
          pytest --version
          python -c "import pytest; assert pytest.__version__.startswith(str(${{ matrix.pytest }}))"
        if: runner.os != 'Windows'

  test_channels:
    name: Test channels
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment-file: [false, environment.yml]
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          environment-file: ${{ matrix.environment-file }}
          environment-name: test-channels
          extra-specs: |
            xtensor
          channels: conda-forge,blah
      - name: check channels are correct
        run: |
          CHANNEL_OPT=$(micromamba config get channels)
          echo $CHANNEL_OPT
          if [[ "$CHANNEL_OPT" != *"conda-forge"* ]]; then
            exit 1;
          fi
          if [[ "$CHANNEL_OPT" != *"blah"* ]]; then
            exit 1;
          fi
          if [[ "${{ matrix.environment-file }}" != "false" ]]; then
            if [[ "$CHANNEL_OPT" != *"defaults"* ]]; then
              exit 1;
            fi
          fi

  test_environment_without_name:
    name: "Test environment.yml without name: attribute"
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          environment-name: noname
          environment-file: .github/workflows/resources/environment_without_name.yml

      - run: micromamba list -n noname | grep -q xtensor
        shell: bash

  test_extra_specs:
    name: Test extra-specs
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          environment-file: environment.yml
          environment-name: myenv
          extra-specs: |
            click
            sel(linux): xtensor
            sel(osx): cmake
            sel(win): ninja

      - name: list environment
        run: |
          micromamba list

      - name: check presence
        if: runner.os == 'linux'
        run: |
          if ! micromamba list | grep -q click; then exit 1; fi
          if ! micromamba list | grep -q xtensor; then exit 1; fi
          if micromamba list | grep -q cmake; then exit 1; fi
          if micromamba list | grep -q ninja; then exit 1; fi

      - name: check presence
        if: runner.os == 'macos'
        run: |
          if ! micromamba list | grep -q click; then exit 1; fi
          if micromamba list | grep -q xtensor; then exit 1; fi
          if ! micromamba list | grep -q cmake; then exit 1; fi
          if micromamba list | grep -q ninja; then exit 1; fi

      - name: check presence
        if: runner.os == 'windows'
        run: |
          if ! micromamba list | grep -q click; then exit 1; fi
          if micromamba list | grep -q xtensor; then exit 1; fi
          if micromamba list | grep -q cmake; then exit 1; fi
          if ! micromamba list | grep -q ninja; then exit 1; fi

  test_channel_priority:
    name: Test channel-priority
    timeout-minutes: 10
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v2
      
      - name: Modify environemnt.yml to require flexible channel priority
        run: |
          contents = open("environment.yml").read()
          open("environment.yml", "w").write(contents.replace("python", "pkgs/main::python"))
        shell: python

      - name: install mamba
        uses: ./
        with:
          channel-priority: flexible
          environment-file: environment.yml

      - name: test
        run: |
          cat ~/.condarc
          grep "channel_priority: flexible" ~/.condarc
          micromamba list | grep -E 'python\s+3\.8' | grep -qv conda-forge

  test_condarc_file:
    name: Test condarc-file
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: create .condarc
        run: |
          echo "# sentinel" > mycondarc

      - name: install mamba
        uses: ./
        with:
          environment-file: environment.yml
          condarc-file: mycondarc

      - name: test
        run: |
          cat ~/.condarc
          grep "# sentinel" ~/.condarc

  test_condarc_options:
    name: Test condarc-options
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./
        with:
          environment-file: environment.yml
          condarc-options: |
            verify_ssl: false
            proxy_servers:
              xxx: https://example.com
            create_default_packages:
              - pip >1

      - name: test
        run: |
          cat ~/.condarc
          grep "verify_ssl: false" ~/.condarc
          grep "xxx: " ~/.condarc
          grep "  - pip >1" ~/.condarc
