name: Basic tests
on:
  push:
    branches:
      - main
  pull_request: null

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test_bash:
    name: Test bash
    timeout-minutes: 10
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - run: |
          echo <<EOF
          channel_alias: https://blah.com/t/${BLAH}/get
          channels: [conda-forge]
          custom_multichannels:
            conda-forge: [https://conda.anaconda.org/conda-forge]
          EOF

      - name: install mamba
        uses: ./
        with:
          environment-file: environment.yml
          environment-name: myenv

      - run: |
          cat ~/.condarc
