name: test
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./

      - name: run python in powershell
        shell: powershell
        run: |
          python -VV
          python -c "import numpy"
          echo "MAMBA_EXE=$Env:MAMBA_EXE"
          which micromamba
          python test/test_path.py
        if: runner.os == 'Windows'

      - name: run python in cmd.exe
        shell: cmd /C call {0}
        run: |
          python -VV
          python -c "import numpy"
          micromamba --help
          echo "MAMBA_EXE=%MAMBA_EXE%"
          where micromamba
          python test/test_path.py
        if: runner.os == 'Windows'

      - name: run python in bash
        shell: bash -l {0}
        run: |
          python -VV
          python -c "import numpy"
          micromamba --help
          echo "MAMBA_EXE=$MAMBA_EXE"
          which micromamba
          python test/test_path.py

      # - name: run python in zsh
      #   shell: zsh -l {0}
      #   run: |
      #     python -VV
      #     python -c "import numpy"
      #     micromamba --help
      #     micromamba activate test
      #     echo "MAMBA_EXE=$MAMBA_EXE"
      #     which micromamba
      #     python test/test_path.py
      #   if: runner.os == 'macOS'