name: Test options
on:
  push:
    branches:
      - main
  pull_request: null

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_channels:
    name: Test channels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment-file: [false, environment.yml]
        condarc-file: [null, /tmp/condarc]
    steps:
      - uses: actions/checkout@v2

      - name: Create .condarc
        run: |
          echo "channels: [conda-forge, defaults]" > /tmp/condarc
        if: matrix.condarc-file != 'null'

      - name: install mamba
        uses: ./
        with:
          environment-file: ${{ matrix.environment-file }}
          environment-name: test-channels
          extra-specs: |
            xtensor
          channels: conda-forge,blah
          condarc-file: ${{ matrix.condarc-file }}
