name: Test options
on:
  push:
    branches:
      - main
  pull_request: null

defaults:
  run:
    shell: bash -el {0}

jobs:
  test_channels:
    name: Test channels
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment-file: [false, environment.yml]
        #condarc-file: [null, /tmp/condarc]
        condarc-file: [/tmp/condarc]
    steps:
      - uses: actions/checkout@v2

      - name: Create .condarc
        run: |
          #echo -e "channels: [conda-forge, defaults]\r\n" > /tmp/condarc
          python -c "import os; open(os.path.expanduser('~/.condarc'), 'wb').write(b'channel_alias: https://conda.prod.quantco.cloud/t/${CONDA_API_KEY}/get\r\n\r\nchannels:\r\n  - qc-internal\r\n  - quantco_main\r\n  - conda-forge\r\n\r\ncustom_channels:\r\n  quantco_main: https://${CONDA_CHANNEL_UPLOAD_USER}:${CONDA_CHANNEL_UPLOAD_PASSWORD}@conda.quantco.cloud\r\n\r\ncustom_multichannels:\r\n  conda-forge:\r\n    - https://conda.anaconda.org/conda-forge\r\n')"
        if: matrix.condarc-file

      - name: install mamba
        uses: ./
        with:
          environment-file: ${{ matrix.environment-file }}
          environment-name: test-channels
          extra-specs: |
            xtensor
          channels: conda-forge,blah
          condarc-file: ${{ matrix.condarc-file }}

      - run: python -c 'import os; print(open(os.path.expanduser("~/.condarc"), "rb").read())'
