name: test
on:
  push: null
  pull_request: null

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: beckermr/provision-with-micromamba@main

      - name: run python
        shell: bash -l -euo pipefail {0}
        run: |
          python -c "import numpy"
