name: test
on:
  push:
    branches:
      - main
  pull_request: null
  workflow_dispatch:


jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: install mamba
        uses: ./

      - name: run python in powershell
        shell: powershell
        run: |
          python -VV
          python -c "import numpy"
          echo "MAMBA_EXE=$Env:MAMBA_EXE"
        if: runner.os == 'Windows'

      - name: run python in cmd.exe
        shell: cmd
        run: |
          python -VV
          python -c "import numpy"
          micromamba --help
          echo "MAMBA_EXE=%MAMBA_EXE%"
        if: runner.os == 'Windows'

      - name: run python in bash
        shell: bash -l {0}
        run: |
          python -VV
          python -c "import numpy"
          micromamba --help
          echo "MAMBA_EXE=$MAMBA_EXE"

      - name: run python in zsh
        shell: zsh -l {0}
        run: |
          python -VV
          python -c "import numpy"
          micromamba --help
          echo "MAMBA_EXE=$MAMBA_EXE"
        if: runner.os == 'macOS'