name: Basic tests
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test_xxx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Conda environment with Micromamba
        #uses: mamba-org/provision-with-micromamba@main
        uses: ./
        with:
          channels: conda-forge
          extra-specs: |
            python=3.8
