name: test
on:
  push:
    branches:
      - main
  pull_request: null

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
    name: test
    steps:
      - uses: actions/checkout@v2

      - name: run python
        shell: bash -l {0}
        run: |
          cat ~/.bash_profile

      - name: install mamba
        uses: ./

      - name: run python
        shell: bash -l {0}
        run: |
          cat ~/.bash_profile
          python -c "import numpy"
